[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "nibelheim"
authors = [{ name = "luwqz1", email = "howluwqz1@gmail.com" }]
maintainers = [{ name = "luwqz1", email = "howluwqz1@gmail.com" }]
dynamic = ["version"]
description = "A simple, fast, and reliable SDK for Remnawave."
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.14"
dependencies = [
    "certifi (>=2026.2.25)",
    "saronia (>=1.5.1)",
    "wreq (>=0.10.2)",
    "openretcon",
]
keywords = [
    "async",
    "asyncio",
    "fast",
    "rnet-http-client",
    "msgspec-models",
    "oas",
    "openapi",
    "openapi-schema",
    "sdk",
    "nibel",
    "nibelheim",
    "remna",
    "remnawave",
    "remna-api",
    "remnawave-api",
    "xray",
    "miohomo",
    "client",
]
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Quality Assurance",
    "Topic :: Utilities",
    "Typing :: Typed",
]

[project.urls]
Homepage = "https://github.com/luwqz1/nibelheim"
Repository = "https://github.com/luwqz1/nibelheim"
"Bug Tracker" = "https://github.com/luwqz1/nibelheim/issues"

[dependency-groups]
dev = [
    "ruff>=0.15.9,<1",
    "basedpyright>=1.39.0,<2",
    "tomlkit>=0.14.0",
    "pytest>=9.0.3,<10",
    "packaging>=26.0,<30",
    "pytest-asyncio>=1.3.0,<2",
    "pytest-cov>=7.1.0,<8",
    "pytest-mock>=3.15.1,<4",
    "pre-commit>=4.5.1,<5",
]

[tool.hatch.version]
path = "src/nibel/__meta__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/nibel"]

[tool.uv.sources]
fntypes = { git = "https://github.com/luwqz1/kungfu", rev = "types" }
openretcon = { git = "https://github.com/luwqz1/OpenRetcon", rev = "main" }

[tool.uv]
package = true

[tool.ruff]
line-length = 160
target-version = "py314"

[tool.ruff.format]
quote-style = "double"
docstring-code-line-length = "dynamic"

[tool.ruff.lint]
select = [
  "I",
  "D",
  "N",
  "PLR",
  "Q",
  "COM",
  "TC",
  "YTT",
  "SIM",
  "RUF022",
]
ignore = [
  "COM812",
  "N805",
  "N818",
  "TC001",
  "TC002",
  "TC003",
  "TC004",
  "D100",
  "D101",
  "D102",
  "D103",
  "D104",
  "D105",
  "D107",
  "D202",
  "D203",
  "D205",
  "D209",
  "D211",
  "D213",
  "D400",
  "D401",
  "D404",
  "D415",
  "PLR2004",
  "PLR0911",
  "PLR0912",
  "PLR0913"
]
fixable = ["ALL"]
exclude = [".venv", ".idea", "docs"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]

[tool.pyright]
include = ["src"]
typeCheckingMode = "strict"
pythonPlatform = "All"
pythonVersion = "3.14"
reportMissingImports = true
reportMissingTypeStubs = false
reportSelfClsParameterName = false
