from __future__ import annotations

import typing
from datetime import date, datetime
from uuid import UUID

import msgspec
import msgspex
import saronia

from .enums import *


class BandwidthStatsBase(msgspex.Model, kw_only=True):
    start: msgspex.isodatetime = msgspex.field(converter=msgspex.From[str | datetime])
    """Start date"""

    end: msgspex.isodatetime = msgspex.field(converter=msgspex.From[str | datetime])
    """End date"""


class StatsNodesUsageBase(msgspex.Model, kw_only=True):
    top_nodes_limit: int = msgspex.field(name="topNodesLimit")
    """Limit of top nodes to return"""

    start: date = msgspex.field(converter=msgspex.From[str | date])
    """Start date (YYYY-MM-DD)"""

    end: date = msgspex.field(converter=msgspex.From[str | date])
    """End date (YYYY-MM-DD)"""


@saronia.json
class PostUsersControllerRevokeUserSubscriptionSignature(msgspex.Model, kw_only=True):
    uuid: saronia.Path[UUID] = msgspex.field(converter=msgspex.From[str | UUID])
    """UUID of the user"""

    revoke_only_passwords: bool | None = msgspex.field(default=None, name="revokeOnlyPasswords")
    """Optional. If true, only passwords will be revoked, without changing the short UUID (Subscription URL)."""

    short_uuid: typing.Annotated[str, msgspec.Meta(min_length=6, max_length=48)] | None = msgspex.field(default=None, name="shortUuid")
    """Optional. If not provided, a new short UUID will be generated by Remnawave. Please note that it is strongly recommended to allow Remnawave to generate the short UUID."""


@saronia.path
class GetPublicSubscriptionControllerSubscriptionByClientTypeSignature(msgspex.Model, kw_only=True):
    client_type: SubscriptionControllerGetSubscriptionByClientTypeClientType = msgspex.field(name="clientType")
    """Client type"""

    short_uuid: str = msgspex.field(name="shortUuid")
    """Short UUID of the user"""


@saronia.json
class GetProtectedSubscriptionsControllerSubpageConfigByShortUuidSignature(msgspex.Model, kw_only=True):
    short_uuid: saronia.Path[str] = msgspex.field(name="shortUuid")
    """Short UUID of the user"""

    request_headers: dict[str, str] = msgspex.field(name="requestHeaders")


@saronia.query
class GetBandwidthStatsControllerNodeUserUsageSignature(BandwidthStatsBase, kw_only=True):
    uuid: saronia.Path[UUID] = msgspex.field(converter=msgspex.From[str | UUID])
    """UUID of the node"""


@saronia.query
class GetBandwidthStatsControllerStatsNodeUsersUsageSignature(msgspex.Model, kw_only=True):
    uuid: saronia.Path[UUID] = msgspex.field(converter=msgspex.From[str | UUID])
    """UUID of the node"""

    top_users_limit: int = msgspex.field(name="topUsersLimit")
    """Limit of top users to return"""

    start: date = msgspex.field(converter=msgspex.From[str | date])
    """Start date (YYYY-MM-DD)"""

    end: date = msgspex.field(converter=msgspex.From[str | date])
    """End date (YYYY-MM-DD)"""


@saronia.query
class GetBandwidthStatsControllerUserUsageByRangeSignature(BandwidthStatsBase, kw_only=True):
    uuid: saronia.Path[UUID] = msgspex.field(converter=msgspex.From[str | UUID])
    """UUID of the user"""


@saronia.query
class GetBandwidthStatsControllerUsersGetStatsNodesUsageSignature(StatsNodesUsageBase, kw_only=True):
    uuid: saronia.Path[UUID] = msgspex.field(converter=msgspex.From[str | UUID])
    """UUID of the user"""


@saronia.query
class GetBandwidthStatsControllerNodesGetStatsNodesUsageSignature(StatsNodesUsageBase, kw_only=True):
    pass


__all__ = (
    "GetBandwidthStatsControllerNodeUserUsageSignature",
    "GetBandwidthStatsControllerNodesGetStatsNodesUsageSignature",
    "GetBandwidthStatsControllerStatsNodeUsersUsageSignature",
    "GetBandwidthStatsControllerUserUsageByRangeSignature",
    "GetBandwidthStatsControllerUsersGetStatsNodesUsageSignature",
    "GetProtectedSubscriptionsControllerSubpageConfigByShortUuidSignature",
    "GetPublicSubscriptionControllerSubscriptionByClientTypeSignature",
    "PostUsersControllerRevokeUserSubscriptionSignature",
)
